### ISSUE TITLE
In github's light theme can't see the engine logo from readme, on main page of project 

### ISSUE THREAD

**Issue by ygroeg** [Quark-Hell/Alpha_Engine#9]
![image](https://github.com/Quark-Hell/Alpha_Engine/assets/93899192/eff0f445-57db-49f3-855a-3a48947a751f)
tested in chromium, firefox

**Comment by Quark-Hell** [comment]
it's probably because of the image format. I save logo as .png without background. Thanks for your issue, i fix this a little latter.

**Comment by ygroeg** [comment]
> i fix this a little latter.

> wontfix tag

:) people judge book by its cover. Although light theme is less popular, somebody won't understand why there is a gap in readme with link to image hosting website.

**Comment by Quark-Hell** [comment]
I added a background to the icon, now it should work
